package com.eazybytes.eazyschool.controller;

import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.web.authentication.logout.SecurityContextLogoutHandler;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;


@Controller
public class LoginController {
	
	// Explain: Here when the end-user try to access some page that need to be authenticated, 
	// The form Login in ProjectSecurityConfig.java will redirect to the page login.html with the help of LoginController
	// In here, It is not required to accept 2 value: "error" and "logout" since all 2 of them have "required = false"
 	@RequestMapping(value = "/login", method = {RequestMethod.POST, RequestMethod.GET})
	public String displayLoginPage(@RequestParam(value = "error",required = false) String error,
									@RequestParam(value = "logout",required = false) String logout,
									@RequestParam(value = "register",required = false)String register,
									Model model) {
		// This code only execute when the end-user type wrong account or password, it will trigger the function failureURL("/login?error=true") in ProjectSecurityConfig.java
 		// Because We are taking value "error" in URL, we use @RequestParam 
 		String errorMessge = null;
 		// Since Error contain a value, it will display the error message
		if(error != null) {
			errorMessge = "Username or Password is Incorrect !!";
			
		}
		// Same for the Logout message 
		else if(logout != null) {
			errorMessge = "You have been successfully logged out !!";
		}
		else if (register != null) {
			errorMessge = "You registration successful. Login in with registered credentials !!";
		}
		//--------------------
		model.addAttribute("errorMessge",errorMessge);
		return "login.html";
	}
 	
 	// This function will handle the log out process due to the enable of CSRF protection in ProjectSecurityCOnfig.java
 	// In most case, Whenever we enable the CSRF protection in the Spring Boot Project, The Logout form need to be configured because it hold the CSRF token along with the website token storing inside the cookies
 	// The CSRF token is automatically generated by Spring Security framework 
 	@GetMapping("/logout")
 	public String logoutPage(HttpServletRequest request, HttpServletResponse response) {
 		Authentication auth = SecurityContextHolder.getContext().getAuthentication();
 		if(auth != null) {
 			new SecurityContextLogoutHandler().logout(request, response, auth);
 		}
 		
 		// The content of "redirect:/login?logout=true" will execute the function displayLoginPage with the logout required = true
 		return "redirect:/login?logout=true";
 	}
 	
}
